### PR TITLE
a first stab at fixing issue #8

### PR DESCRIPTION
**Pull request by parmentelat**
I cannot test it however, as I can't find the solutions code (the private repo) any more...
I did search under ue12-p21/ but to no avail 
where was that again ?

### CODE REVIEW

**Comment by Kehrlann** [comment]
Here: https://github.com/boisgera/notebook

**Comment by Kehrlann** [comment]
Tested, it works except for `test_to_starboard_html`. Pushed an additional fix.

**Review by Kehrlann — APPROVED** [review]
👍 lgtm

**Comment by parmentelat** [comment]
originally added here a comment, but that turned out ato be  separate issue so I moved it in #11

**Comment by parmentelat** [comment]
let's do this then

**Pull request merged**
